// All stylesheets are loaded eagerly, in the same order the app used before
// screens were lazy-loaded. Several screens share class names defined in other
// screens' CSS (e.g. .search-box, .empty-state), so keeping one global cascade
// avoids missing styles when only one role's JS chunk is downloaded.
import './components/common/Button.css'
import './components/common/AppChrome.css'
import './components/admin/shared/AdminManagement.css'
import './components/admin/restaurants/RestaurantManagement.css'
import './components/common/DeleteButton.css'
import './components/common/EditButton.css'
import './components/common/ToggleButton.css'
import './components/common/SaveButton.css'
import './components/common/CancelButton.css'
import './components/admin/food/RestaurantSelector.css'
import './components/admin/AdminDashboard/AdminDashboard.css'
import './components/admin/delivery/DeliveryManagement.css'
import './components/admin/payment/PaymentMethodManagement.css'
import './components/admin/settings/DeliverySettings.css'
import './components/admin/orders/OrderManagement.css'
import './components/admin/restaurants/RestaurantOrders.css'
import './components/admin/users/UserManagement.css'
import './components/admin/finances/FinanceManagement.css'
import './components/admin/drivers/DriverManagement.css'
import './components/admin/shared/AdminMobile.css'
import './components/auth/Auth.css'
import './components/student/StudentHome.css'
import './components/student/StudentMenu.css'
import './components/student/StudentCheckout.css'
import './components/student/StudentPayment.css'
import './components/student/StudentOrders.css'
import './components/driver/DriverDashboard.css'
import './components/common/PageLoader.css'
